### ISSUE TITLE
How to request a revision on a document 'in review' ?

### ISSUE THREAD

**Issue by Pitoune** [worldia/textmaster-api#64]
I am not sure how to ask for a revision when a document is in status 'in_review'.
Should I create a support message ?
Is there a way to reject a translation with a message of what is not correct ?

**Comment by aponsin** [comment]
Yes, I agree it is not necessarily very clear. But indeed you have to create a "support message" ressource when you document is in review in order to be able to "send it back" to the author (resulting in an "incomplete" status). And within the support message attributes you can specify the reason why this document is being "rejected". I hope this clears things.

**Comment by Pitoune** [comment]
OK I got it.
I would try it on document 573d96b6d876f6000b376316 from project 573d96b5ac09e9000b5194c1. But the document is still in `quality_control`. Could you put it `in_review` ?

**Comment by Pitoune** [comment]
Thanks !
